version: 2.1

jobs:
    pre-build:
        docker:
            - image: circleci/node:lts-stretch
        steps:
            - checkout
            - restore_cache:
                  keys: 
                    - frontend-deps-{{ checksum "package.json" }}
                    - frontend-deps-
            - run:
                name: Install dependencies
                command: |
                  make install
                  # Install hadolint
                  sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                  sudo chmod +x /bin/hadolint
            - run:
                name: Run lint checks
                command: |
                  make lint
            - run:
                name: Run unit tests
                command: |
                  make test

    build:
        docker:
            - image: circleci/python:3.7-stretch
        steps:
            - checkout
            - setup_remote_docker:
                version: 19.03.13
            - run:
                name: Build and push docker image
                command: |
                  docker build -t ${DOCKERHUB_USERNAME}/${IMAGE_NAME} .
                  echo ${DOCKERHUB_PASSWORD} | docker login -u ${DOCKERHUB_USERNAME} --password-stdin
                  docker push ${DOCKERHUB_USERNAME}/${IMAGE_NAME}

workflows:
  default:
    jobs:
      - pre-build
      - build:
          requires:
            - pre-build